export const data = {
    examRules: {
        cameraCaptureDescription: "Your video and audio will be captured and streamed to the monitoring room throughout the whole exam, turning your camera off will result in suspending the exam.",
        cameraCaptureDescriptionStudent: "Student's video and audio will be captured and streamed to the monitoring room throughout the whole exam, turning camera off will result in suspending the exam.",
        cameraCaptureTitle: "Camera capture",
        cameraCheckTitle: "Test your camera",
        cameraDescription: "Click on the \"Start Camera\" button, and make sure that your video is clear and visible before you continue.",
        cameraRecordDescription: "Your video and audio will be recorded and saved along with your answers, please note that the administration can view your recordings while grading your answers.",
        cameraRecordDescriptionStudent: "Student's video and audio will be recorded and saved along with the answers, and the administration can view each student's recordings while grading the answers.",
        cameraRecordTitle: "Camera recording",
        consoleRuleWarning: "Dev console is not allowed",
        consoleRuleWarningDesc: "Opening the dev console will terminate your exam session.",
        copyPasteDescription: "Any text you copy or paste inside the exam room will be recorded. When grading your answers, administration can see the text you copied.",
        copyPasteDescriptionStudent: "Any text student copy or paste inside the exam room will be recorded. When grading students' answers, administration can see copied text.",
        copyPasteTitle: "Copy paste detection",
        cursorRuleWarning: "Mouse cursor is outside the window",
        cursorRuleWarningDesc: "Moving the mouse cursor out of the exam window will result in a warning",
        disableRightClickDescription: "You can't use the right click in your mouse during the exam. Note that opening the dev console will immediately suspend your exam and might result in terminating your session.",
        disableRightClickDescriptionStudent: "Student can't use the right click in the mouse during the exam. Also opening the dev console will immediately suspend student's exam and might result in terminating the session.",
        disableRightClickTitle: "No mouse right click",
        disableTabSwitchDescription: "You can't change the application or the browser tabs during the exam. You can't resize the application window during the exam. Any of these actions will result in a warning and might terminate your exam session.",
        disableTabSwitchDescriptionStudent: "Student can't change the application or the browser tabs during the exam. Also can't resize the application window during the exam. Any of these actions will result in a warning and might terminate student's exam session.",
        disableTabSwitchTitle: "No Tab Switch",
        enableFullscreenDescription: "Full screen mode will be enabled during the exam. You can't exit the full screen mode or resize the window. Doing so will result in a warning and might terminate your exam session completely.",
        enableFullscreenTitle: "Full Screen Mode",
        fullscreenRuleWarning: "Fullscreen Mode Must be Enabled",
        fullscreenRuleWarningDesc: "Exiting fullscreen mode during the exam might result in warning",
        iUnderstand: "I Understand",
        makeFullscreen: "Make Fullscreen",
        micCheckDescription: "Make sure you select the right input device and that your audio is loud and clear before you continue. You can Press the \"test\" button to check your audio.",
        micCheckTitle: "Test your mic",
        noSecondScreenDescription: "No second or external monitors during the exam. No broadcast or presentation devices are allowed During the exam. If the system detects such devices, it will result in a warning and might terminate your exam session completely. ",
        noSecondScreenTitle: "No extra screens",
        screenCaptureDescription: "Your entire screen and screen audio will be captured and streamed to the monitoring room throughout the whole exam, turning screen share off will suspend the exam.",
        screenCaptureDescriptionStudent: "Student's entire screen and screen audio will be captured and streamed to the monitoring room throughout the whole exam, turning screen share off will suspend the exam.",
        screenCaptureTitle: "Screen capture",
        screenCheckTitle: "Share your screen",
        screenDescription: "Click on the \"Start\" button, and share your entire screen. Make sure the screen audio is enabled. You can't enter the exam if you don't follow these instructions.",
        screenRecordTitle: "Screen recording",
        screenRecordDescription: "Your entire screen and screen audio will be recorded and saved along with your answers, please note that the administration can view your recordings while grading your answers.",
        screenRecordDescriptionStudent: "Student's entire screen and screen audio will be recorded and saved along with the answers, and the administration can view each student's recordings while grading the answers.",
        secondMonitorRuleWarning: "No second monitors allowed",
        secondMonitorRuleWarningDesc: "Please disconnect any extra monitors or presentation devices, breaking this rule might result in a warning",
        waitingForExamHint: "When the timer hits zero, you should see an \"Enter\" button bellow. Make sure you follow all the past instructions. Not doing so might result in a warning, restarting the whole security check process, or sometimes terminating your exam session completely.",
        windowFocusWarning: "Exam window should always be focused",
        windowFocusWarningDesc: "Switching tabs or un focusing the exam window might result in a warning",
        audioDisconnectedTitle: "Mic has stopped",
        cameraDisconnectedTitle: "Camera has stopped",
        screenDisconnectedTitle: "Screen share has stopped",
        mediaDisconnectedDesc: "Please wait for a while we try to reconnect. The exam should continue automatically. If that doesn't work, try checking your device or try restarting the exam session from the top right corner",
        consoleRuleTitle: "No dev console",
        consoleRuleDescription: "Using the dev console, or the \"Inspect Element\" feature is forbidden in any exam. Breaking this rule might result in terminating your exam session completely or banning you from the platform.",
        cursorOutOfScreenTitle: "Cursor inside window",
        cursorOutOfScreenDescription: "Your mouse cursor should always stay inside the exam window during the exam. Breaking this rule might result in a warning and sometimes terminating your exam session completely.",
        extraRules: 'Extra rules',
        attempts: 'Attempts',
        attemptDesc: 'How many times students can take the exam',
        attemptDuration: 'Attempt duration (minutes)',
        attemptDurationDesc: 'How many (minutes) long each exam attempt is',
        noRules: "No rules",
        noRulesDesc: "No monitoring. Everything is allowed",
        basic: "Basic",
        basicDesc: "Browser rules, but no camera or screen monitoring",
        videoMonitoring: "Video monitoring",
        videoMonitoringDesc: "Browser rules with camera and screen monitoring",
        custom: "Custom",
        customDesc: "Pick the rules you want to apply",
        minLatencyAllowedTitle: "Minimum latency allowed",
        minLatencyAllowedDescription: "Minimum latency allowed in minutes",
        attemptDurationInMinutes: 'Attempt duration in minutes',
        numberOfAttemptsAllowed: 'Number of attempts allowed',
        examDurationInMin: 'Exam duration in minutes',
    },
    media: {
        blockedHintStep1: "1. Click the camera-blocked icon in your browser's address bar",
        blockedHintStep2: "2. Grant access, then refresh the page",
        cameraBlockedHintTitle: "OpExams needs access to your camera.",
        cameraBlockedTitle: "Your camera is blocked",
        hideScreenBarDescription: "Click on the hide button below to hide the screen bar before you   continue.",
        hideScreenBarTitle: "Press 'Hide' to continue",
        micBlockedHintTitle: "OpExams needs access to your microphone.",
        micBlockedTitle: "Your microphone is blocked",
        notMainScreenError: "You must share your entire screen",
        notSharingScreenAudio: "You must enable audio from the share screen popup",
        streamingUnsupported: "Streaming is not supported",
        unknownDevice: "Unknown device",
        unknownError: "Unknown error",
        deviceNotFound: "Device not found"
    }
}